### ISSUE TITLE
Fails to build with LLVM 9.0.0rc1

### ISSUE THREAD

**Issue by t6** [vanhauser-thc/AFLplusplus#40]
LLVM 9.0.0 is scheduled to be released on 2019-08-28.  afl++ currently fails to build against it:
```
clang++90 `llvm-config90 --cxxflags` -Wl,-znodelete -fno-rtti -fpic -O2 -pipe -fstack-protector-strong -fno-strict-aliasing   -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DVERSION=\"++2.53c\" -Wno-variadic-macros -shared compare-transform-pass.so.cc -o ../compare-transform-pass.so `llvm-config90 --ldflags`  -fstack-protector-strong
--
compare-transform-pass.so.cc:85:13: error: no viable conversion from 'llvm::Function' to 'llvm::Function *'
Function* tolowerFn = cast<Function>(c);
^           ~~~~~~~~~~~~~~~~~
In file included from compare-transform-pass.so.cc:22:
In file included from /usr/local/llvm90/include/llvm/IR/IRBuilder.h:22:
In file included from /usr/local/llvm90/include/llvm/IR/BasicBlock.h:22:
In file included from /usr/local/llvm90/include/llvm/IR/Instruction.h:21:
In file included from /usr/local/llvm90/include/llvm/IR/DebugLoc.h:17:
In file included from /usr/local/llvm90/include/llvm/IR/TrackingMDRef.h:16:
In file included from /usr/local/llvm90/include/llvm/IR/Metadata.h:28:
In file included from /usr/local/llvm90/include/llvm/IR/Constant.h:16:
In file included from /usr/local/llvm90/include/llvm/IR/User.h:23:
In file included from /usr/local/llvm90/include/llvm/IR/Use.h:29:
In file included from /usr/local/llvm90/include/llvm/Support/CBindingWrapping.h:17:
/usr/local/llvm90/include/llvm/Support/Casting.h:58:24: error: cannot initialize a parameter of type 'const llvm::Value *' with an rvalue of type 'const llvm::FunctionCallee *'
return To::classof(&Val);
^~~~
/usr/local/llvm90/include/llvm/Support/Casting.h:77:32: note: in instantiation of member function 'llvm::isa_impl<llvm::Function, llvm::FunctionCallee, void>::doit' requested here
return isa_impl<To, From>::doit(Val);
^
/usr/local/llvm90/include/llvm/Support/Casting.h:132:36: note: in instantiation of member function 'llvm::isa_impl_cl<llvm::Function, const llvm::FunctionCallee>::doit' requested here
return isa_impl_cl<To,FromTy>::doit(Val);
^
/usr/local/llvm90/include/llvm/Support/Casting.h:143:70: note: in instantiation of member function 'llvm::isa_impl_wrap<llvm::Function, const llvm::FunctionCallee, const llvm::FunctionCallee>::doit' requested here
typename simplify_type<const Y>::SimpleType>::doit(Val);
^
/usr/local/llvm90/include/llvm/Support/Casting.h:257:10: note: in instantiation of function template specialization 'llvm::isa<llvm::Function, llvm::FunctionCallee>' requested here
assert(isa<X>(Val) && "cast<Ty>() argument of incompatible type!");
^
compare-transform-pass.so.cc:85:25: note: in instantiation of function template specialization 'llvm::cast<llvm::Function, llvm::FunctionCallee>' requested here
Function* tolowerFn = cast<Function>(c);
^
/usr/local/llvm90/include/llvm/IR/Function.h:774:36: note: passing argument to parameter 'V' here
static bool classof(const Value *V) {
^
2 errors generated.
```
See https://reviews.freebsd.org/P287 for the full log.

**Comment by vanhauser-thc** [comment]
known and documented in llvm_mode/README.llvm_mode

the issue is that llvm completely rewrite how the compiler passes work - plus some API changes.

@hexcoder- is on it, but will take time. 

patches etc are welcome :)

**Comment by hexcoder-** [comment]
Yes, I can confirm this. The changes introduced by llvm/clang 9.0 are pretty scary.
In standard mode using CC=clang, the instrumentation check fails now :-(

**Comment by hexcoder-** [comment]
clang 9.0 radically reduces basic blocks, so all paths in the test program go through the same blocks. This means an input of 0, 1, or any other character will give the same bitmap.
But no input gives a different bitmap, so I will use that.

**Comment by hexcoder-** [comment]
It should work now with commit [07df1e3](https://github.com/vanhauser-thc/AFLplusplus/commit/07df1e303419a642b96750411af99b586d0ea5a0).
Please test and report back. Thanks.

**Comment by t6** [comment]
Seems to build and work ok now. Thanks.

**Comment by hexcoder-** [comment]
Fixed.
